### PR TITLE
update installation script for 2.5

### PR DESCRIPTION
**Pull request by Jooho**
## Description

This add new scripts for 2.5 odh/rhods operator.

## How Has This Been Tested?

After you login to a new fresh openshift cluster, then execute these commands
~~~
git clone git@github.com:Jooho/caikit-tgis-serving.git
cd caikit-tgis-serving/demo/kserve

# Install kserve + dependencies
export TARGET_OPERATOR=rhods
export CHECK_UWM=false

# If you are using ROSA, please add this too
# export PLATFORM=rosa 

./scripts/install_2.5/kserve-install.sh

# Deploy model
./scripts/test/deploy-model-grpc.sh
./scripts/test/deploy-model-http.sh

# Test
./scripts/test/grpc-call.sh
./scripts/test/http-call.sh

# Delete isvc/minio
./scripts/test/delete-model.sh

# Uninstall kserve and dependencies
./scripts/uninstall_2.5/kserve-uninstall.sh
./scripts/uninstall_2.5/dependencies-uninstall.sh
~~~

### CODE REVIEW

**Comment by esposem** [comment]
I can confirm this works on freshly created Azure self managed OCP cluster! Thanks a lot!

Only one suggestion, if you want you can add to this PR also this change here
```
diff --git a/demo/kserve/scripts/test/grpc-console.sh b/demo/kserve/scripts/test/grpc-console.sh
index 36d76ba..c6132e2 100755
--- a/demo/kserve/scripts/test/grpc-console.sh
+++ b/demo/kserve/scripts/test/grpc-console.sh
@@ -15,10 +15,11 @@ source "$(dirname "$(realpath "$0")")/../utils.sh"
 echo
 echo "Wait until runtime is READY"
 
-wait_for_pods_ready "serving.kserve.io/inferenceservice=caikit-example-isvc" "${TEST_NS}"
-oc wait --for=condition=ready pod -l serving.kserve.io/inferenceservice=caikit-example-isvc -n ${TEST_NS} --timeout=300s
+ISVC_NAME=caikit-tgis-isvc-grpc
+wait_for_pods_ready "serving.kserve.io/inferenceservice=${ISVC_NAME}" "${TEST_NS}"
+oc wait --for=condition=ready pod -l serving.kserve.io/inferenceservice=${ISVC_NAME} -n ${TEST_NS} --timeout=300s
 
-export KSVC_HOSTNAME=$(oc get ksvc caikit-example-isvc-predictor -n ${TEST_NS} -o jsonpath='{.status.url}' | cut -d'/' -f3)
+export KSVC_HOSTNAME=$(oc get ksvc "${ISVC_NAME}"-predictor -n ${TEST_NS} -o jsonpath='{.status.url}' | cut -d'/' -f3)
 
 echo "test namespace: $TEST_NS"
 echo "ksvc hostname: $KSVC_HOSTNAME"
```

Otherwise I can open another PR :)

**Comment by dtrifiro** [comment]
@Jooho do we need to have both `demo/kserve/scripts/install` and `demo/kserve/scripts/install_2.5`? I'd rather update them in-place

**Comment by Jooho** [comment]
@dtrifiro ODH is still 2.4 and the way how to install Kserve is too different. When odh release 2.5, then we can replace it.

**Comment by Jooho** [comment]
@esposem updated

**Pull request merged**
