### PR TITLE
refactor: updated makefile and docker to allow development for apple silicon

### PR DESCRIPTION
**Pull request by z103cb**
Apple silicon updates to the Makefile and Dockerfile

Related to #167

### CODE REVIEW

**Comment by ckadner** [comment]
@z103cb -- I am Apple M2 Pro. I just cloned this project for the first time. When I try to set up this project (your branch or main) I run into this error:

```
  • Installing nvidia-nvjitlink-cu12 (12.3.101): Failed

  RuntimeError

  Unable to find installation candidates for nvidia-nvjitlink-cu12 (12.3.101)
```

Did you encounter this? Did I miss a few steps? Could you point out a workaround? 🙏🏻

**Comment by dtrifiro** [comment]
Tagging @tarilabs because he has experience on devcontainers :)

**Comment by tarilabs** [comment]
Thanks for the ping @dtrifiro 

Sharing current experience as a dev and contributor from [Model Registry team](https://github.com/opendatahub-io/model-registry); we have Python MLMD wheel by Google as a dependency and it's limited in supported archs (see [here](https://pypi.org/project/ml-metadata/#files) mainly x86 only)

We are investigating two options.
The "improving" solution would be to have a version of the python dependency not requiring binaries or specific archs; something like [this hack](https://github.com/tarilabs/ml-metadata-remote#readme), but maybe better structured 😅 (thanks again Daniele for the suggestion)

The DevContainer option is as follows.
As a Apple-silicon / ARM-based dev, I need to keep the dependencies of python (the x86 dependency) as-is.
I create a qemu x86 based VM for docker.
In my case I use colima:

```sh 
colima start --vz-rosetta --vm-type vz --arch x86_64 --cpu 4 --memory 8
```

Then I define this `.devcontainer/devcontainer.json`:
```json
{
	"name": "Python 3",
	// "image": "mcr.microsoft.com/devcontainers/python:1-3.10-bullseye"
	"build": {
		"dockerfile": "Dockerfile"
	},
	"runArgs": [
		"--network=host"
	],
	"customizations": {
		"vscode": {
			"extensions": [
				// does not work well in DevContainer: "robocorp.robotframework-lsp",
				"d-biehl.robotcode"
			]
		}
	},
//...
}
```

The `network=host` allow me from _inside_ the devcontainer to reach any "service" exposed on my laptop (host).
The vscode.extensions pre-loads additional extensions I need in VSCode to be executing from inside the DevContainer.

and this `.devcontainer/Dockerfile`:
```docker
FROM mcr.microsoft.com/devcontainers/python:1-3.10-bullseye

# Here I use the USER from the FROM image
ARG USERNAME=vscode
ARG GROUPNAME=vscode

# Here I use the UID/GID from _my_ computer, as I'm _not_ using Docker Desktop
ARG USER_UID=501
ARG USER_GID=20

RUN groupmod --gid $USER_GID -o $GROUPNAME \
    && usermod --uid $USER_UID --gid $USER_GID $USERNAME \
    && chown -R $USER_UID:$USER_GID /home/$USERNAME

# General setup which is "cached" for convenience
RUN pip install -U pip setuptools
RUN pip install -U poetry
RUN pip install -U "ml-metadata==1.14.0"
RUN pip install -U robotframework
RUN pip install -U robotframework-requests
RUN pip install -U PyYAML
```

The group/user is needed as on Mac anything _but_ Docker Desktop will need to set correct FS permissions. (more details here: `https://github.com/devcontainers/spec/issues/325`).
The RUN pip install "caches" the local installation (inside the DevContainer) of some wheels I always need.
The kicker is the line `RUN pip install -U "ml-metadata==1.14.0"`, that pip install would fail on Apple-silicon/ARM-based machine.

Then with VSCode I use "reopen folder inside container".

It's not super fast because x86 is emulated via Rosetta, but works "good enough" for me to survive.

The experience is similar to when on GitHub.com you press dot `.` and you get a VSCode "inside something", except is local.

For non-VSCode user but leveraging LSP, an SDK is available too afaik.

I have an action item open in Model Registry to document "everything I found so far when developing on Apple-silicon/ARM" and looking to share back here when available.

In the meantime, hope this is helpful :)

**Comment by tarilabs** [comment]
> I am using Rancher Desktop app for my docker install with apple virtualisation support (not QEMU).

I made a mistake in my writing (still need to organize the notes) as colima image is indeed Rosetta (not qemu).

edited comment

**Comment by z103cb** [comment]
@ckadner, @dtrifiro and @tarilabs I propose we move the discussion on the use of dev containers in this issue: #172.  I do not want to keep this PR open longer than is necessary.

Thoughts?

**Pull request merged**
