### PR TITLE
Disable jaeger

### PR DESCRIPTION
**Pull request by Jooho**
## Description

This fix https://github.com/opendatahub-io/caikit-tgis-serving/issues/116

## How Has This Been Tested?

With a fresh cluster, you can test it
## script check
**odh installation**
~~~
git clone --branch 20231011_doc_update git@github.com:Jooho/caikit-tgis-serving.git
cd caikit-tgis-serving/demo/kserve
export TARGET_OPERATOR=odh 
export CHECK_UWM=false

./scripts/install/kserve-install.sh
./scripts/test/deploy-model.sh
./scripts/test/grpc-call.sh

# Verify this use mtls: true
oc get smcp -o yaml minimal -n istio-system|grep mtls
...
        mtls: true
...

./scripts/uninstall/kserve-uninstall.sh
./scripts/uninstall/dependencies-uninstall.sh
~~~

**rhods installation**
~~~
export TARGET_OPERATOR=rhods
export CHECK_UWM=false

./scripts/install/kserve-install.sh
./scripts/test/deploy-model.sh
./scripts/test/grpc-call.sh

# Verify this use mtls: true
oc get smcp -o yaml minimal -n istio-system|grep mtls
...
        mtls: true
...

./scripts/uninstall/kserve-uninstall.sh
./scripts/uninstall/dependencies-uninstall.sh
~~~

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by Jooho** [comment]
@bdattoma please review this.

**Comment by bdattoma** [comment]
lgtm- Did you run it in a cleaned/fresh cluster?

**Review by danielezonca — APPROVED** [review]
LGTM, even if it looks more like a bug in SM 🤔 it should be optional

**Review by lucferbux — APPROVED** [review]
/lgtm

**Review by spolti — APPROVED** [review]

**Review by lucferbux — APPROVED** [review]
/lgtm

**Comment by dtrifiro** [comment]
> @Jooho I guess it can be manually merged, did this repo has changed the config to not allow merge?

Yes, we'd ideally like to use rebase as default. CI will have to be updated (see https://github.com/openshift/release/pull/44830)

**Pull request merged**
