### PR TITLE
WIP: update caikit-nlp to the current upstream's main commit

### PR DESCRIPTION
**Pull request by kpouget**
WIP PR  to build a `caikit-tgis-serving` image including the latest changes `caikit-nlp` changes. In particular:
* https://github.com/caikit/caikit-nlp/pull/204
* https://github.com/caikit/caikit/pull/472

which should resolve this issue I'm facing: https://github.com/caikit/caikit-nlp/issues/237

**DO NOT MERGE.**

### CODE REVIEW

**Comment by kpouget** [comment]
Hello @vaibhavjainwiz, could you give the `/ok-to-test` on the PR, so that Prow builds the image? I'd like to test the fix (=update `caikit-nlp` to main for my performance tests)

**Comment by kpouget** [comment]
hum, I thought `ci/prow/images` should push the image to quay.io, but it doesn't apparently :/

**Comment by kpouget** [comment]
I built and pushed the image there:
* quay.io/kpouget/catalogs:caikit-tgis-serving | quay.io/kpouget/catalogs@sha256:fd8c9488bbf94e3840e55782f9973d96bdb9c37a46b30c39c37f2c8c56e8077d

but from what I can see, that doesn't solve the problem :/

**Comment by kpouget** [comment]
```
quay.io/kpouget/catalogs@sha256:d2eceb2687c60dd8edeb6775eb9783a8a96ab605570aec3d1ead3f83730b2e8b
```
FYI, this image works, after this PR has been merge https://github.com/caikit/caikit-nlp/pull/241

**Comment by Xaenalt** [comment]
Oh, no ci/prow/images won't, but pr-image-mirror will, looks like we don't have that on the caikit repo, we'll add that

**Comment by kpouget** [comment]
Closing, I will turn this into an issue.

**Comment by kpouget** [comment]
Closing in favor of https://github.com/opendatahub-io/caikit-tgis-serving/issues/120

**Pull request closed without merging**
